parameters:
    ccdn_forum_admin.category.manager.class:              CCDNForum\AdminBundle\Entity\Manager\CategoryManager
    ccdn_forum_admin.category.form.insert.handler.class:  CCDNForum\AdminBundle\Form\Handler\CategoryInsertFormHandler
    ccdn_forum_admin.category.form.update.handler.class:  CCDNForum\AdminBundle\Form\Handler\CategoryUpdateFormHandler
    ccdn_forum_admin.category.form.type.class:            CCDNForum\AdminBundle\Form\Type\CategoryType
                    
    ccdn_forum_admin.board.manager.class:                 CCDNForum\AdminBundle\Entity\Manager\BoardManager
    ccdn_forum_admin.board.form.insert.handler.class:     CCDNForum\AdminBundle\Form\Handler\BoardInsertFormHandler
    ccdn_forum_admin.board.form.update.handler.class:     CCDNForum\AdminBundle\Form\Handler\BoardUpdateFormHandler
    ccdn_forum_admin.board.form.type.class:               CCDNForum\AdminBundle\Form\Type\BoardType
    
services:
    ccdn_forum_admin.category.form.type:
        class:  %ccdn_forum_admin.category.form.type.class%
        arguments:  [@doctrine]        
    ccdn_forum_admin.category.manager:
        class:  %ccdn_forum_admin.category.manager.class%
        arguments:  [@doctrine, @service_container]              
    ccdn_forum_admin.category.form.insert.handler:
        class:  %ccdn_forum_admin.category.form.insert.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.category.manager]
    ccdn_forum_admin.category.form.update.handler:
        class:  %ccdn_forum_admin.category.form.update.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.category.manager]
        
    ccdn_forum_admin.board.form.type:
        class:  %ccdn_forum_admin.board.form.type.class%
        arguments:  [@doctrine]        
    ccdn_forum_admin.board.manager:
        class:  %ccdn_forum_admin.board.manager.class%
        arguments:  [@doctrine, @service_container]   
    ccdn_forum_admin.board.form.insert.handler:
        class:  %ccdn_forum_admin.board.form.insert.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.board.manager]
    ccdn_forum_admin.board.form.update.handler:
        class:  %ccdn_forum_admin.board.form.update.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_forum_admin.board.manager]